#!/usr/bin/env python
from scanner import scanner
import wx
import wx.grid



class GridFrame(wx.Frame):
    grid = None
    def __init__(self, parent):

        wx.Frame.__init__(self, parent)

        # Create a wxGrid object
        self.grid = wx.grid.Grid(self, -1)
        # Then we call CreateGrid to set the dimensions of the grid
        # (100 rows and 10 columns in this example)
        self.grid.CreateGrid(1,4)

        self.Show()

class ScannerGrid:

    def __init__(self,grid):
        self.grid = grid
        self.grid.ClearGrid()
        self.grid.DeleteRows( 0, self.grid.GetNumberRows())
        self.grid.AppendRows(50)


if __name__ == '__main__':

    app = wx.App(0)
    frame = GridFrame(None)
    ScannerGrid(frame.grid)
    app.MainLoop()